language: node_js
node_js:
- '8'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
    repo: ngengs/ng-style-builder
